# Generated by Django 6.0.2 on 2026-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_category_name_en_category_name_ru_category_name_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="course",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="course",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="course",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="course",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="course",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_order_en",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="lessson order"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_order_ru",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="lessson order"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_order_uz",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="lessson order"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="type_en",
            field=models.CharField(max_length=64, null=True, verbose_name="type"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="type_ru",
            field=models.CharField(max_length=64, null=True, verbose_name="type"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="type_uz",
            field=models.CharField(max_length=64, null=True, verbose_name="type"),
        ),
        migrations.AddField(
            model_name="module",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="module",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="module",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="name"),
        ),
    ]
